"""Calibrated UR kinematics from the YAML generated by ``ur_calibration``.

The calibration YAML contains six corrected fixed transforms read by the
official UR description.  This module composes the same fixed transforms with
six local Z-axis joint rotations, then estimates the active TCP offset from the
real ``tcp_pose_broadcaster`` pose at startup.
"""
from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import yaml

JOINT_KEYS = ("shoulder", "upper_arm", "forearm", "wrist_1", "wrist_2", "wrist_3")


def rpy_matrix(roll: float, pitch: float, yaw: float) -> np.ndarray:
    cr, sr = math.cos(roll), math.sin(roll)
    cp, sp = math.cos(pitch), math.sin(pitch)
    cy, sy = math.cos(yaw), math.sin(yaw)
    rx = np.array([[1.0, 0.0, 0.0], [0.0, cr, -sr], [0.0, sr, cr]])
    ry = np.array([[cp, 0.0, sp], [0.0, 1.0, 0.0], [-sp, 0.0, cp]])
    rz = np.array([[cy, -sy, 0.0], [sy, cy, 0.0], [0.0, 0.0, 1.0]])
    return rz @ ry @ rx


def quaternion_matrix(x: float, y: float, z: float, w: float) -> np.ndarray:
    n = math.sqrt(x * x + y * y + z * z + w * w)
    if n < 1e-12:
        raise ValueError("Zero quaternion")
    x, y, z, w = x / n, y / n, z / n, w / n
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ], dtype=np.float64)


def pose_matrix(position: np.ndarray, quaternion_xyzw: np.ndarray) -> np.ndarray:
    T = np.eye(4, dtype=np.float64)
    T[:3, :3] = quaternion_matrix(*np.asarray(quaternion_xyzw, dtype=np.float64).reshape(4))
    T[:3, 3] = np.asarray(position, dtype=np.float64).reshape(3)
    return T


def rotation_log(R: np.ndarray) -> np.ndarray:
    """SO(3) logarithm as a rotation vector."""
    R = np.asarray(R, dtype=np.float64).reshape(3, 3)
    cos_theta = float(np.clip((np.trace(R) - 1.0) * 0.5, -1.0, 1.0))
    theta = math.acos(cos_theta)
    if theta < 1e-8:
        return 0.5 * np.array([R[2, 1] - R[1, 2], R[0, 2] - R[2, 0], R[1, 0] - R[0, 1]])
    denom = 2.0 * math.sin(theta)
    axis = np.array([R[2, 1] - R[1, 2], R[0, 2] - R[2, 0], R[1, 0] - R[0, 1]]) / denom
    return axis * theta


class CalibratedURKinematics:
    def __init__(self, fixed_transforms: list[np.ndarray]) -> None:
        if len(fixed_transforms) != 6:
            raise ValueError("Expected six calibrated transforms")
        self.fixed_transforms = [np.asarray(T, dtype=np.float64).reshape(4, 4) for T in fixed_transforms]
        self.tcp_offset = np.eye(4, dtype=np.float64)

    @classmethod
    def from_yaml(cls, path: str | Path) -> "CalibratedURKinematics":
        path = Path(path).expanduser().resolve()
        with path.open("r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle)
        kin = data.get("kinematics", {}) if isinstance(data, dict) else {}
        transforms: list[np.ndarray] = []
        for key in JOINT_KEYS:
            values = kin.get(key)
            if not isinstance(values, dict):
                raise ValueError(f"Missing kinematics.{key} in {path}")
            T = np.eye(4, dtype=np.float64)
            T[:3, :3] = rpy_matrix(
                float(values["roll"]), float(values["pitch"]), float(values["yaw"])
            )
            T[:3, 3] = [float(values["x"]), float(values["y"]), float(values["z"])]
            transforms.append(T)
        return cls(transforms)

    @staticmethod
    def _joint_rotation(angle: float) -> np.ndarray:
        c, s = math.cos(float(angle)), math.sin(float(angle))
        T = np.eye(4, dtype=np.float64)
        T[:3, :3] = [[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]]
        return T

    def flange_transform(self, q: np.ndarray) -> np.ndarray:
        q = np.asarray(q, dtype=np.float64).reshape(6)
        T = np.eye(4, dtype=np.float64)
        for fixed, angle in zip(self.fixed_transforms, q):
            T = T @ fixed @ self._joint_rotation(float(angle))
        return T

    def tcp_transform(self, q: np.ndarray) -> np.ndarray:
        return self.flange_transform(q) @ self.tcp_offset

    def estimate_tcp_offset(self, q: np.ndarray, measured_tcp: np.ndarray) -> np.ndarray:
        measured_tcp = np.asarray(measured_tcp, dtype=np.float64).reshape(4, 4)
        self.tcp_offset = np.linalg.inv(self.flange_transform(q)) @ measured_tcp
        return self.tcp_offset.copy()

    def position(self, q: np.ndarray) -> np.ndarray:
        return self.tcp_transform(q)[:3, 3].copy()

    def geometric_jacobian(self, q: np.ndarray, eps: float = 2e-6) -> np.ndarray:
        """Numerical 6x6 Jacobian [linear; angular] in the base frame."""
        q = np.asarray(q, dtype=np.float64).reshape(6)
        J = np.zeros((6, 6), dtype=np.float64)
        for i in range(6):
            qp, qm = q.copy(), q.copy()
            qp[i] += eps
            qm[i] -= eps
            Tp = self.tcp_transform(qp)
            Tm = self.tcp_transform(qm)
            J[:3, i] = (Tp[:3, 3] - Tm[:3, 3]) / (2.0 * eps)
            # R_plus * R_minus^T gives the base-frame incremental rotation.
            J[3:, i] = rotation_log(Tp[:3, :3] @ Tm[:3, :3].T) / (2.0 * eps)
        J[~np.isfinite(J)] = 0.0
        return J

    def solve_twist(
        self,
        q: np.ndarray,
        linear_velocity: np.ndarray,
        angular_velocity: np.ndarray | None = None,
        damping: float = 0.02,
        orientation_weight_m: float = 0.15,
    ) -> tuple[np.ndarray, float]:
        """Damped least-squares inverse with orientation hold.

        Rotational rows are multiplied by a characteristic length so that linear
        and angular residuals have comparable numerical units.
        """
        J = self.geometric_jacobian(q)
        v = np.zeros(6, dtype=np.float64)
        v[:3] = np.asarray(linear_velocity, dtype=np.float64).reshape(3)
        if angular_velocity is not None:
            v[3:] = np.asarray(angular_velocity, dtype=np.float64).reshape(3)
        Jw = J.copy()
        vw = v.copy()
        Jw[3:, :] *= float(orientation_weight_m)
        vw[3:] *= float(orientation_weight_m)
        A = Jw @ Jw.T + float(damping) ** 2 * np.eye(6)
        qdot = Jw.T @ np.linalg.solve(A, vw)
        singular = np.linalg.svd(Jw, compute_uv=False)
        condition = float("inf") if singular[-1] < 1e-10 else float(singular[0] / singular[-1])
        return qdot, condition
